### PR TITLE
feat(#8): Support RedHat based systems

### PR DESCRIPTION
**Pull request by aairey**
Also update to latest checksum as script has changed last month.

### CODE REVIEW

**Comment by aairey** [comment]
@markosamuli can we merge this?
I am using this and it works fine.

**Comment by markosamuli** [comment]
Happy to add this! 👌

Do you want to add your name to the README for this? 

Would be great to have some kind of tests for Fedora (or any other Red Hat based distro). I have been running Debian/Ubuntu tests in Docker and then running those on GitHub Actions.

**Review by markosamuli — APPROVED** [review]

**Comment by aairey** [comment]
I don't mind the README addition, there's a contirbutors list in the GitHub UI now on the right-hand side.

I don't see any github actions in this repo, only travis still.

I am personally using it so it is fine, but I agree it could use some test.
Still, could we merge it? :)

**Comment by aairey** [comment]
Hi @markosamuli can we please merge this?

**Comment by aairey** [comment]
@markosamuli bump

**Comment by aairey** [comment]
@markosamuli as previously discussed and reviewed, could we just merge this please?

FYI @huyz if your fork has these changes too and you will maintain it, I may switch to your fork.

**Comment by huyz** [comment]
@aairey I'd have to look into what it takes to maintain/test distributions that I don't myself use, as I pretty much only use Ubuntu these past 2 decades.  But I'll let you know if I start getting serious

**Comment by aairey** [comment]
We could setup the test matrix with molecule and github actions for this.

**Comment by huyz** [comment]
@aairey  Yeah we could.  I've been trying to learn how to do that.  Still working on it.

**Comment by aairey** [comment]
> @aairey Yeah we could. I've been trying to learn how to do that. Still working on it.

Maybe you could have a look at this:
https://github.com/aairey/ansible-role-dotfiles/tree/main/.github
Or any of geerlingguy's roles.

**Review by markosamuli — DISMISSED** [review]
I don't have a RedHat based system to test this, but hopefully this will now work on yours. 

I was using Travis before they effectively stopped supporting open source projects. My Ansible roles didn't make the cut and I didn't have the time to set this role with new CI / test set up on GitHub Actions or something else that doesn't cost me extra. 

Happy for the checksum to be removed or made optional as I'm not actively using this and will not be bumping it up every now and then.

**Comment by markosamuli** [comment]
I've added support for Fedora 37 in #12

**Comment by aairey** [comment]
Thanks for merging!

Nothing major, but somehow my username was misspelled as @aarey in the release notes ^.^

**Comment by markosamuli** [comment]
@aairey I've corrected your name now. Thanks for letting me know.

**Comment by markosamuli** [comment]
Closing this as the changes are no longer compatible with the latest codebase.

**Comment by aairey** [comment]
Thanks, I guess :)

**Pull request closed without merging**
